### ISSUE TITLE
Make entities separated by newline instead of comma and space for readability

### ISSUE THREAD

**Issue by melyux** [gmlupatelli/blueprints_repo#4]
For `unavailable_entities_notification.yaml`, you just have to change the end of `variables` → `entities` from `{{result.sensors|join(', ')}}` to `{{result.entities|join('\n')}}`.

For `unavailable_entities_notification.yaml`, you just have to change the end of `variables` → `sensors` from `{{result.sensors|join(', ')}}` to `{{result.entities|join('\n')}}`.

**Comment by gmlupatelli** [comment]
#9

**Comment by gmlupatelli** [comment]
Changed by #9
