### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by TonyDicken1964** [gmlupatelli/blueprints_repo#7]
Sorry for the dumb question - I would REALY love to use this blueprint, but what do I add here to get the sensors data?

![image](https://user-images.githubusercontent.com/101743718/198826915-bdb9e949-c166-44c8-bd7c-5caae7e3a67d.png)

Thanks

Tony

**Comment by gmlupatelli** [comment]
You need to use {{sensors}}. It is replaced with a list of sensors names.
